language: erlang
otp_release:
  - 20.2
  - 19.3
  - 18.3
  - 17.5
  - R16B
script: rebar compile
after_script:
  - rebar clean
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
